disabled_rules: # rule identifiers to exclude from running
  - trailing_comma
  - line_length
  - force_cast
  - identifier_name
  - large_tuple
included:
  - MasterMind
  - MasterMindTests
  - MasterMindUITests
excluded:
  - Pods
