# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'MasterMind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  # Pods for MasterMind

  target 'MasterMindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MasterMindUITests' do
    # Pods for testing
  end

end
